export const GENERATE_WALLET = 'GENERATE_WALLET';
export const ENCRYPT_WALLET = 'ENCRYPT_WALLET';
export const DECRYPT_WALLET = 'DECRYPT_WALLET';
export const ADD_WALLET = 'ADD_WALLET';
export const REMOVE_WALLET = 'REMOVE_WALLET';
export const SIGNED_WEB3_ACTION = 'SIGNED_WEB3_ACTION';
// VOTING ACTIONS
export const WEB3_CREATE_VOTING = 'WEB3_CREATE_VOTING';
export const WEB3_CREATE_VARIANT = 'WEB3_CREATE_VARIANT';
export const WEB3_ADD_MEMBER = 'WEB3_ADD_MEMBER';
export const WEB3_START_VOTING = 'WEB3_START_VOTING';
export const WEB3_ADD_VOTE = 'WEB3_ADD_VOTE';
export const WEB3_FINISH_VOTING = 'WEB3_FINISH_VOTING';

export const WEB3_RESULTS = 'WEB3_RESULTS';
export const WEB3_GET_RESULTS = 'WEB3_GET_RESULTS';
export const WEB3_SET_STATE = 'WEB3_SET_STATE';
